### PR TITLE
Add displayname to new workitems

### PR DESCRIPTION
**Pull request by alexaxb**
When creating new workitems, add Id and title to the displayname the same was as the console does. This is because the console searches in the displayname attribute.

### CODE REVIEW

**Comment by AdhocAdam** [comment]
Quick test with some Incidents and you are correct. But it looks like things are different _just for Incidents_.

- Incidents use -
- Service Requests use :
- Change Requests use :
- Problems use :

**Comment by alexaxb** [comment]
Yea, look at that..I guess it would be too easy if it where consistent for all the work item types ;)
Nice catch!

**Comment by AdhocAdam** [comment]
After another look, it appears that there is even _more_ variance between the DisplayName property across Work Item types. I've gone ahead and updated these on the branch.

image

**Comment by alexaxb** [comment]
Thanks for the correction!

**Comment by AdhocAdam** [comment]
And thank you for raising this!

**Pull request merged**
