### PR TITLE
Add existing user check to function New-CMDBUser

### PR DESCRIPTION
**Pull request by lakam99**
There may be cases where users without TargetAddresses exist. In this case, SMLets will assume there is no user for this email when the reality is that the user exists but they do not have a TargetAddress. This change seeks to resolve that issue.

### CODE REVIEW

**Comment by lakam99** [comment]
As you stated @AdhocAdam, this method is intrusive and assumes the user wants the connector to modify user emails. I've created a less intrusive pull request #377

**Comment by AdhocAdam** [comment]
For the sake of clarity, what this pull request made me wonder is _what_ is the scenario where a user exists but does not have an associated email _and_ you'd want to set it via the connector.

That said - maybe that scenario doesn't even exist. I'm just thinking outloud. Whichever the case, I'll check out the other PR you mentioned here. 👍

**Comment by lakam99** [comment]
Well, that scenario, unfortunately, existed in my production environment. There are a lot of users with no email formatted in a SMLets Exchange Connector style that were created with a task/runbook made before I arrived. Users made by the task/runbook weren't the only ones like this, but the majority were. I guess this issue so far has only affected my environment, but I think adding an extra check to make sure the user _really_ exists before giving up would only improve the connector.

**Comment by AdhocAdam** [comment]
Ahhhhh. Ok. That clears things up. 👍

**Pull request closed without merging**
